game:assets/scripts/menu.o assets/scripts/menu_functions.o
	gcc menu.o -o program -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf
assets/scripts/menu.o:menu.c
	gcc -c menu.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf
assets/scripts/menu_functions.o:assets/scripts/menu_functions.c
	gcc -c assets/scripts/menu_functions.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf