EnS:main.o function.o
	gcc main.o -o Ens -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf
main.o:main.c
	gcc -c main.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf
function.o:function.c
	gcc -c function.c -lSDL -lSDL_mixer -lSDL_image -lSDL_ttf

